### ISSUE TITLE
polygons_to_ofPath(): const vector<ofPolyline> push_back() issue

### ISSUE THREAD

**Issue by musiko** [bakercp/ofxClipper#10]
Line 177 in **ofxClipper.cpp**:
_path.getOutline()_ returns a const vector so that _push_back(ofPolyline)_ has no legal conversion. I tested it on Windows platform. Is this error platform-specific or it happens on Mac too?

``` C++
void ofxClipper::polygons_to_ofPath(ClipperLib::Paths& polygons,ofPath& path) {
    vector<ClipperLib::Path>::iterator iter;
    for(iter = polygons.begin(); iter != polygons.end(); iter++) {
        path.getOutline().push_back(polygon_to_ofPolyline((*iter)));         // This line
    }
}
```

Compilation error:

``` C++
Error   C2663   'std::vector<ofPolyline,std::allocator<_Ty>>::push_back': 2 overloads have no legal conversion for 'this' pointer
```

**Comment by CarstenHoyer** [comment]
I just opened #16, turned out the fix in #11 still works, so I closed it again. 

Is there a reason why it has not been merged @bakercp?

Best regards.

**Comment by bakercp** [comment]
The reason it hasn't been merged is just time / attention.  I'm trying to get this fixed up now @CarstenHoyer .  Thanks for your attention and persistence ...

**Comment by bakercp** [comment]
This should be solved with the latest version.  Please reopen if the issue persists.
