### ISSUE TITLE
Const vector errors

### ISSUE THREAD

**Issue by autr** [bakercp/ofxClipper#13]
Hi, getting these errors;

![screen shot 2017-07-30 at 22 13 09](https://user-images.githubusercontent.com/1035590/28757137-7ba17bc6-7574-11e7-980c-7dd800d68959.png)
![screen shot 2017-07-30 at 22 13 22](https://user-images.githubusercontent.com/1035590/28757138-7ba1e5e8-7574-11e7-8ca8-691d5d65b26a.png)

Compiles fine on my other machine though both are identical running 0.9.8 w. SDK 10.12

**Comment by bakercp** [comment]
I need more information ... don't know what branch you're using, what the code looks like, if you regenerated the project files, etc.

**Comment by paolo-scoppola** [comment]
Hi bakercp,

I've just downloaded the master branch today. I'm compiling on OSX 10.11.6, Xcode 7.0.1 and OF 0.9.8. I get very similar errors (see also errors #10)

![screenshot 2017-09-02 13 33 23](https://user-images.githubusercontent.com/6932431/29995167-5744e2e8-8fe3-11e7-9e8c-e30a885c4a7a.png)

![screenshot 2017-09-02 13 33 27](https://user-images.githubusercontent.com/6932431/29995170-60b7306a-8fe3-11e7-9952-3dd9efdecdac.png)

Probably it need just an update to the latest OF version,

thanks a lot,

Paolo

**Comment by bakercp** [comment]
This should be solved with the latest version.  Please reopen if the issue persists.
